name: lint&tests
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен — выполняет какую-то задачу
      # checkout — клонирует репозиторий
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      # run – произвольная bash-команда
      - run: npm ci
      - run: make lint
      - run: make test-coverage
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

